repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.17.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./modules/eks-with-managed-ng"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.89.1"
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        exclude: ^modules/
      - id: terraform_checkov
        args:
          # - --args=--quiet
          - --args=--skip-check CKV_TF_1
